export default Object.freeze({
    LOGIN: "Login",
    REGISTER: "Register",
    OTP: "Otp",
    SUCCESSFUL: "Successful",
    DASHBOARD: "Dashboard",
    MEMBERS: "Members",
    MEMBERDETAILS: "MemberDetails",
    NEWEDITMEMBER: "NewEditMember",
    VIEWMEALS: "ViewMeals",
    MESS: "Mess",
    UPDATE_MESS: "UpdateMess",
    SESSIONS: "Sessions",
    NEWEDITSESSION: "NewEditSession",
    DAILYEXPENSES: "DailyExpenses",
    NEWEDITDAILYEXPENSE: "NewEditDailyExpense",
    FIXEDEXPENSES: "FixedExpenses",
    NEWEDITFIXEDEXPENSE: "NewEditFixedExpense",
    PROFILE: "Profile",
    EDITPROFILE: "EditProfile",
    CHANGE_PASSWORD: "ChangePassword",
    DEPOSITS: "Deposits",
    ADDWITHDRAWDEPOSIT: "AddWithdrawDeposit",
    DEPOSITHISTORY: "DepositHistory",
    ASSIGNEDDATE: "AssignedDate",
    ADDASSIGNEDDATE: "AddAssingedDate"
});